version: '3'
services:
  client:
    container_name: client-dashboard
    build: 
      context: ./client
      dockerfile: Dockerfile
    environment:
      REACT_APP_DEV_ENV: "TRUE"
    image: client-dashboard
    ports:
      - 3000:3000
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
    image: server-dashboard
    ports:
      - 8080:8080