name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker compose
      run: docker-compose build
    - name: Run Docker compose
      run: docker-compose up
      if: always()
        run: docker-compose down
